language: cpp
compiler: gcc
sudo: required
dist: xenial

os: 
  - osx
  - linux
  
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      tools/travis/before_install_linux.sh
    else
      tools/travis/before_install_macos.sh
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      tools/travis/install_linux.sh
    else
      tools/travis/install_macos.sh
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      tools/travis/script_linux.sh
    else
      tools/travis/script_macos.sh
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      tools/travis/script_linux.sh
    else
      tools/travis/script_macos.sh
    fi
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  # - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

