environment:
  QTDIR: C:/Qt/5.12/msvc2017_64
  BOOST_ROOT: c:/Libraries/boost_1_69_0

configuration: Release

image: Visual Studio 2017
platform: x64

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S
  - pip install sphinx quark-sphinx-theme

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -T host=x64 -A x64 -DSEGMENT_RELEASE=1 -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" -DBOOST_ROOT="%BOOST_ROOT%" ..
  - cmake --build . --config Release --target Package

artifacts:
  - name: Installer
    path: 'build/segment-*.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: L6H/oYlUaRA+IAUwVeggtyG4T/mhzhx/yqnPwehUGXclLsvXRDiwaEIjXY9gmIvb
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
