environment:
  QTDIR: C:/Qt/5.11/msvc2017_64
  BOOST_ROOT: c:/Libraries/boost_1_67_0

configuration: Release

image: Visual Studio 2017
platform: x64

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S
  - appveyor DownloadFile "https://github.com/OSSIA/score-sdk/releases/download/sdk9/win-audio-sdk.zip" -FileName win-audio-sdk.zip
  - 7z x win-audio-sdk.zip
  - move portaudio c:\portaudio
  - move tbb c:\tbb
  - move ffmpeg c:\ffmpeg

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -T host=x64 -G "Visual Studio 15 2017 Win64" -DSCORE_CONFIGURATION=static-release -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" -DSCORE_ENABLE_LTO=0 ..
  - cmake --build . --config Release --target Package

artifacts:
  - name: Installer
    path: 'build/score-*.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: j0nBV9xVItdG3j6d0gHoyvrzi7TOhAy9/QIeyCbFeP8PTqq7DPr1oYwL5WIkPaXe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
